name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # - name: Checking out node
      #   run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --coverage
        #ci stands for clean-install

  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies
        run: npm ci

      - name: prettier format check
        run: npm run format:check

